### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by trashmanbrah** [megadose/holehe#106]
**Describe the bug**
Running Holhe returns a Syntax Error.

**To Reproduce**
1. run holhe
2. Errored 
**Copy and Paste**
 File "/usr/local/lib/python3.6/dist-packages/holehe/modules/products/samsung.py", line 90
    if found := re.search(phone_number_pattern, req.text):

**Comment by trashmanbrah** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 11, in <module>
    load_entry_point('holehe==1.61', 'console_scripts', 'holehe')()
  File "/usr/local/lib/python3.6/dist-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.6/dist-packages/holehe/core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
  File "/usr/local/lib/python3.6/dist-packages/holehe/core.py", line 46, in import_submodules
    results.update(import_submodules(full_name))
  File "/usr/local/lib/python3.6/dist-packages/holehe/core.py", line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/holehe/modules/products/samsung.py", line 90
    if found := re.search(phone_number_pattern, req.text):

**Comment by SamirPS** [comment]
Do you have the error after the if found ?

**Comment by trashmanbrah** [comment]
Yeah i sent the full record log

**Comment by dkeraudren** [comment]
You are using python 3.6, but samsung.py use the walrus operator which require python at least python 3.8
