### ISSUE TITLE
Holehe has just been updated, you can restart it.

### ISSUE THREAD

**Issue by andre-santos1** [megadose/holehe#107]
**Describe the bug**

When I execute Holehe, I get: 

_Holehe has just been updated, you can restart it._

**To Reproduce**

1. Type `holehe <target_email`
2. Hit enter
4. See error: _Holehe has just been updated, you can restart it._

**Expected behavior**

Holehe was expected to run as it should.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser Chrome
 - Version 22.04 LTS

**Additional context**

Searching the internet I saw this solution:

pip show holehe
and
pip install --upgrade holehe

Running _pip show holehe_ I get:

_ERROR: Exception:

Traceback (most recent call last):

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _parsed_pkg_info

    return self._pkg_info

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__

    raise AttributeError(attr)

AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper

    status = run_func(*args)

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 45, in run

    if not print_results(

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 148, in print_results

    for i, dist in enumerate(distributions):

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 103, in search_packages_info

    required_by = sorted(_get_requiring_packages(dist), key=str.lower)

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 93, in <genexpr>

    in {canonicalize_name(d.name) for d in dist.iter_dependencies()}

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 199, in iter_dependencies

    return self._dist.requires(extras)

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires

    dm = self._dep_map

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map

    self.__dep_map = self._compute_dependencies()

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3032, in _compute_dependencies

    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info

    metadata = self.get_metadata(self.PKG_INFO)

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata

    value = self._get(path)

  File "/home/osint/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get

    with open(path, 'rb') as stream:

FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/usr/local/lib/python3.10/dist-packages/requests-2.28.1.dist-info/METADATA'_

Running _pip3 show holehe_ I get the same error.

Running _pip install --upgrade holehe_ I get:

_Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: holehe in ./.local/lib/python3.10/site-packages (1.60.3)

Collecting holehe

  Using cached holehe-1.61.tar.gz (44 kB)

  Preparing metadata (setup.py) ... error

  error: subprocess-exited-with-error

  

  × python setup.py egg_info did not run successfully.

  │ exit code: 1

  ╰─> [12 lines of output]

      /usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'install_requires'

        warnings.warn(msg)

      /usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'include_package_data'

        warnings.warn(msg)

      /usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'entry_points'

        warnings.warn(msg)

      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

         or: setup.py --help [cmd1 cmd2 ...]

         or: setup.py --help-commands

         or: setup.py cmd --help

      

      error: invalid command 'egg_info'

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

× Encountered error while generating package metadata.

╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

hint: See above for details._

Running _pip3 install --upgrade holehe_ I get the same error

**Comment by UhhhWonse** [comment]
?
