### ISSUE TITLE
ModuleNotFoundError: No module named 'holehe.modules.mails.skeleton'

### ISSUE THREAD

**Issue by spinfal** [megadose/holehe#108]
**Describe the bug**
After installing and trying to use holehe, I receive a `ModuleNotFoundError` error.

**To Reproduce**
1. Run `pip install holehe`
2. Run `holehe email@example.com`

**Expected behavior**
Holehe begins to function as normally, looking for the given email.

**Screenshots**
![Error Screenshot](https://cdn.spin.rip/r/WindowsTerminal_5733876591.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (21H2, build 22000.675)
 - Browser: Firefox
 - Version: 103.0.2

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
```shell
Traceback (most recent call last):
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\Scripts\holehe.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\site-packages\holehe\core.py", line 226, in main
    trio.run(maincore)
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\site-packages\holehe\core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\site-packages\holehe\core.py", line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
  File "C:\Users\domsg\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'holehe.modules.mails.skeleton'
```

**Comment by Manuelq059** [comment]
Run incorrect, please run with:

> * Run `pip3 install holehe`
