### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by sadoj-kuro** [megadose/holehe#115]
**Describe the bug**
when i type holehe <email> i have a syntax error

**Desktop (please complete the following information):**
 - OS: debian 10
 - python: 3.9.1

**Additional context**

Traceback (most recent call last):
  File "/home/debian/.local/bin/holehe", line 10, in <module>
    sys.exit(main())
  File "/home/debian/.local/lib/python3.7/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/home/debian/.local/lib/python3.7/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/debian/.local/lib/python3.7/site-packages/holehe/core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
  File "/home/debian/.local/lib/python3.7/site-packages/holehe/core.py", line 46, in import_submodules
    results.update(import_submodules(full_name))
  File "/home/debian/.local/lib/python3.7/site-packages/holehe/core.py", line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/debian/.local/lib/python3.7/site-packages/holehe/modules/products/samsung.py", line 90

**Comment by Rchatru** [comment]
I have the same problem running on CLI on Raspberry.
