### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Alpha-404** [megadose/holehe#122]
**Describe the bug**
Fails to run

**To Reproduce**
run holehe gmail.com

**Expected behavior**
gets info

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser firefox
 -  version latest

`➜  ~ holehe test@gmail.com
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
  0%|                                                                                                                                                                  | 0/121 [00:00<?, ?it/s]/home/rajaa/.local/lib/python3.9/site-packages/anyio/_backends/_trio.py:164: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  class ExceptionGroup(BaseExceptionGroup, trio.MultiError):
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 111/121 [00:01<00:00, 85.89it/s]Traceback (most recent call last):
  File "/home/rajaa/.local/bin/holehe", line 8, in <module>
    sys.exit(main())
  File "/home/rajaa/.local/lib/python3.9/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/home/rajaa/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/home/rajaa/.local/lib/python3.9/site-packages/holehe/core.py", line 218, in maincore
    await client.aclose()
  File "/home/rajaa/.local/lib/python3.9/site-packages/httpx/_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "/home/rajaa/.local/lib/python3.9/site-packages/httpx/_transports/default.py", line 365, in aclose
    await self._pool.aclose()
  File "/home/rajaa/.local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 9 HTTP requests/responses were still in-flight.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 121/121 [00:02<00:00, 45.66it/s]
➜  ~`

**Comment by Halkenguard** [comment]
Getting the same error on Windows 11, Python 3.11.0. Running via elevated powershell does not change the outcome.

**Comment by alexbarraboldu** [comment]
Hello, I got the same error. Had Python 3.10. After removing it and installing Python 3.11 the error doesn't appear, and the program works as intended.

**Comment by BeatJuice5** [comment]
Having the same issue here, and updating Python hasn't change a thing. I don't know what to do... 

Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
  0%|                                                                                                                                                                  | 0/121 [00:00<?, ?it/s]/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/anyio/_backends/_trio.py:164: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  class ExceptionGroup(BaseExceptionGroup, trio.MultiError):
 93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 112/121 [00:01<00:00, 95.86it/s]Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.8.13/bin/holehe", line 8, in <module>
    sys.exit(main())
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/holehe/core.py", line 218, in maincore
    await client.aclose()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/httpx/_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/httpx/_transports/default.py", line 365, in aclose
    await self._pool.aclose()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 11 HTTP requests/responses were still in-flight.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 121/121 [00:10<00:00,
