### ISSUE TITLE
Runtime Error whenever I use it

### ISSUE THREAD

**Issue by Lunascaped** [megadose/holehe#143]
**Describe the bug**
It always fails saying that some requests were still in flights

**To Reproduce**
Run holehe with any email

Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
  0%|                                                                                          | 0/121 [00:00<?, ?it/s]C:\Users\Luna\AppData\Roaming\Python\Python311\site-packages\anyio\_backends\_trio.py:164: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  class ExceptionGroup(BaseExceptionGroup, trio.MultiError):
 86%|███████████████████████████████████████████████████████████████████▉           | 104/121 [00:00<00:00, 159.32it/s]Traceback (most recent call last):
  File "C:\Program Files\Python311\Scripts\holehe-script.py", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.61', 'console_scripts', 'holehe')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\holehe-1.61-py3.11.egg\holehe\core.py", line 226, in main
    trio.run(maincore)
  File "C:\Users\Luna\AppData\Roaming\Python\Python311\site-packages\trio\_core\_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "C:\Program Files\Python311\Lib\site-packages\holehe-1.61-py3.11.egg\holehe\core.py", line 218, in maincore
    await client.aclose()
  File "C:\Users\Luna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "C:\Users\Luna\AppData\Roaming\Python\Python311\site-packages\httpx\_transports\default.py", line 365, in aclose
    await self._pool.aclose()
  File "C:\Users\Luna\AppData\Roaming\Python\Python311\site-packages\httpcore\_async\connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 17 HTTP requests/responses were still in-flight.
100%|████████████████████████████████████████████████████████████████████████████████| 121/121 [00:10<00:00, 11.79it/s]

**Comment by adasdasdas435345** [comment]
I am a same problem

**Comment by Lunascaped** [comment]
Not sure why this was closed if no solution was presented?
