### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Frintezza1337** [megadose/holehe#145]
How i can fix this error ?

$ holehe test@gmail.com
Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.61', 'console_scripts', 'holehe')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/holehe", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/holehe-1.61-py3.11.egg/holehe/core.py", line 4, in <module>
    import trio
  File "/usr/local/lib/python3.11/dist-packages/trio-0.22.0-py3.11.egg/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/usr/local/lib/python3.11/dist-packages/trio-0.22.0-py3.11.egg/trio/_core/__init__.py", line 9, in <module>
    from ._exceptions import (
  File "/usr/local/lib/python3.11/dist-packages/trio-0.22.0-py3.11.egg/trio/_core/_exceptions.py", line 3, in <module>
    from trio._util import NoPublicConstructor
  File "/usr/local/lib/python3.11/dist-packages/trio-0.22.0-py3.11.egg/trio/_util.py", line 15, in <module>
    from async_generator import isasyncgen
ModuleNotFoundError: No module named 'async_generator'

i use:
Python 3.11.2
Linux kali 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux

**Comment by kimochijrk** [comment]
I have the same problem

**Comment by roothheo** [comment]
try to remove it from the /usr/local/bin then completly install it using git clone and su cause the script need some root permissions
