### ISSUE TITLE
ModuleNotFoundError on kali linux

### ISSUE THREAD

**Issue by FBSANAKONDA** [megadose/holehe#156]
I used pip to install holehe 1.61 on my kali linux machine:
```
$pip install holehe  
Defaulting to user installation because normal site-packages is not writeable
Collecting holehe
  Using cached holehe-1.61-py3-none-any.whl
Requirement already satisfied: termcolor in /usr/lib/python3/dist-packages (from holehe) (1.1.0)
Requirement already satisfied: bs4 in /usr/local/lib/python3.11/dist-packages (from holehe) (0.0.1)
Requirement already satisfied: httpx in /usr/lib/python3/dist-packages (from holehe) (0.23.3)
Requirement already satisfied: trio in /usr/lib/python3/dist-packages (from holehe) (0.22.0)
Requirement already satisfied: tqdm in /usr/lib/python3/dist-packages (from holehe) (4.64.1)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from holehe) (0.4.6)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->holehe) (4.11.2)
Requirement already satisfied: certifi in ./.local/lib/python3.11/site-packages (from httpx->holehe) (2022.12.7)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /usr/lib/python3/dist-packages (from httpx->holehe) (0.16.3)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/lib/python3/dist-packages (from httpx->holehe) (1.5.0)
Requirement already satisfied: sniffio in /usr/lib/python3/dist-packages (from httpx->holehe) (1.2.0)
Requirement already satisfied: idna in ./.local/lib/python3.11/site-packages (from rfc3986[idna2008]<2,>=1.3->httpx->holehe) (2.10)
Installing collected packages: holehe
Successfully installed holehe-1.61
```

Looks everything is good, but when I run it I get this error:
```
$holehe examplemail@gmail.com   
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/home/user/.local/bin/holehe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/home/user/.local/lib/python3.11/site-packages/holehe/core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File `"/home/user/.local/lib/python3.11/site-packages/holehe/core.py",` line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'holehe.modules.osint.__main__'

```
Its probably something I messed up, but I can find a way to fix it. I would really appreciate if you would respond with a fix or fix the issue. 

Greetings, FBS

**Comment by Togeee12** [comment]
Hey, as you can see here: 
File "/home/user/.local/bin/holehe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/home/user/.local/lib/python3.11/site-packages/holehe/core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File `"/home/user/.local/lib/python3.11/site-packages/holehe/core.py",` line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked

the problem is probably caused by not "valid" python configuration. 
What may help: 
-- Complete reinstall of whole package. 
-- Reinstalling python on your machine. 
-- Updating your machine system.
Please let me know if it worked?

**Comment by Togeee12** [comment]
Hey, as you can see here: 
File "/home/user/.local/bin/holehe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/home/user/.local/lib/python3.11/site-packages/holehe/core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File `"/home/user/.local/lib/python3.11/site-packages/holehe/core.py",` line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked

the problem is probably caused by not "valid" python configuration. 
What may help: 
-- Complete reinstall of whole package.
