### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Mdpslater** [megadose/holehe#157]
I get this everytime I run Holehe

Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "C:\Users\mdpsl\AppData\Local\Programs\Python\Python36-32\Scripts\holehe-script.py", line 11, in <module>
    load_entry_point('holehe==1.61', 'console_scripts', 'holehe')()
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\site-packages\holehe\core.py", line 226, in main
    trio.run(maincore)
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\site-packages\holehe\core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\site-packages\holehe\core.py", line 46, in import_submodules
    results.update(import_submodules(full_name))
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\site-packages\holehe\core.py", line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\mdpsl\appdata\local\programs\python\python36-32\lib\site-packages\holehe\modules\products\samsung.py", line 90
    if found := re.search(phone_number_pattern, req.text):
              ^
SyntaxError: invalid syntax

 windows 11
Python 3.11

**Comment by mark-sercombe** [comment]
This project does not use python 3.11 try running it on a lower version

**Comment by Mdpslater** [comment]
I have tried it on 3.6 and get the same issue

**Comment by mark-sercombe** [comment]
I don't personally use windows but I wil spin up a virtual machine and try to reproduce your issue
