### ISSUE TITLE
ModuleNotFoundError on Debian : tputil

### ISSUE THREAD

**Issue by ylacaute** [megadose/holehe#184]
**Describe the bug**
Unable to use the bin holehe, we have a Python error :

```
Traceback (most recent call last):
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/trio-0.23.1-py3.9.egg/trio/_core/_multierror.py", line 365, in <module>
    import tputil
ModuleNotFoundError: No module named 'tputil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foo/.pyenv/versions/3.9.18/bin/holehe", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.61', 'console_scripts', 'holehe')())
  File "/home/foo/.pyenv/versions/3.9.18/bin/holehe", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/holehe-1.61-py3.9.egg/holehe/core.py", line 4, in <module>
    import trio
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/trio-0.23.1-py3.9.egg/trio/__init__.py", line 20, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/trio-0.23.1-py3.9.egg/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/trio-0.23.1-py3.9.egg/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/trio-0.23.1-py3.9.egg/trio/_core/_run.py", line 51, in <module>
    from ._multierror import MultiError, concat_tb
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/site-packages/trio-0.23.1-py3.9.egg/trio/_core/_multierror.py", line 368, in <module>
    import ctypes
  File "/home/foo/.pyenv/versions/3.9.18/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

**To Reproduce**
1. git clone ...
2. cd holehe
3. python3 setup.py install     (using python 3.9.18, with Pyenv)
4. holehe test@gmail.com

**Expected behavior**
Something working

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Debian 12

**Smartphone (please complete the following information):**
 -
 
**Additional context**

pip3 install tputil => not found

**Comment by ylacaute** [comment]
@megadose can you explain how to resolve "ModuleNotFoundError: No module named 'tputil'" please ?
