### ISSUE TITLE
Unexpected keywork argument

### ISSUE THREAD

**Issue by ixotecu** [megadose/holehe#189]
**Describe the bug**
Error while trying to run a simple holehe command like holehe -h or holehe john.doe@example.com

**Error Message**
`Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.11/dist-packages/trio-0.22.2-py3.11.egg/trio/_core/_run.py", line 2093, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.11/dist-packages/holehe/core.py", line 190, in maincore
    check_update()
  File "/usr/local/lib/python3.11/dist-packages/holehe/core.py", line 67, in check_update
    check_version = httpx.get("https://pypi.org/pypi/holehe/json")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpx/_api.py", line 196, in get
    return request(
           ^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpx/_api.py", line 95, in request
    with Client(
         ^^^^^^^
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 686, in __init__
    self._transport = self._init_transport(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 734, in _init_transport
    return HTTPTransport(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpx/_transports/default.py", line 138, in __init__
    self._pool = httpcore.ConnectionPool(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
`

**Desktop**
 - python 3.11.7
 - holehe 1.61

**Additional context**
Worked fine until I ran an update. Tried to uninstall and reinstall but no effect.

**Comment by adkiem** [comment]
I've got the same issue when connecting to OpenAI via `client = OpenAI()` for example.

- Python 3.10.13
- openai 1.12.0
