### ISSUE TITLE
Syntax error after entering email for holehe to search

### ISSUE THREAD

**Issue by daler-nout24** [megadose/holehe#202]
I use holehe via Terminal on mac. I'm on Python 3.6 (I updated to higher versions and saw no improvement, just made my other OSINT methods not work so I went back). I have not changed anything about how I use it, other stuff like Ignorant is working fine, but as of a few weeks ago Holehe just won't work for me and says (after spitting out code for a bit) that theres a syntax error. When I search an email 'holehe example@example.com' I get this result:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/holehe", line 11, in <module>
    load_entry_point('holehe==1.61', 'console_scripts', 'holehe')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/holehe/core.py", line 226, in main
    trio.run(maincore)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/holehe/core.py", line 199, in maincore
    modules = import_submodules("holehe.modules")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/holehe/core.py", line 46, in import_submodules
    results.update(import_submodules(full_name))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/holehe/core.py", line 44, in import_submodules
    results[full_name] = importlib.import_module(full_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/holehe/modules/products/samsung.py", line 90
    if found := re.search(phone_number_pattern, req.text):
              ^
SyntaxError: invalid syntax
admins-iMac:~ User$ 

the last part is the issue. What am I doing wrong here? I've tried other emails in case that somehow tripped it up but nothing.

**Comment by daler-nout24** [comment]
I found a fix! I had manually installed holehe initially, now that i've uninstalled it and cloned it instead, plus put 'pip3 install trio' that seemed to fix it.

**Comment by daler-nout24** [comment]
I found a fix! I had manually installed holehe initially, now that i've uninstalled it and cloned it instead, plus put 'pip3 install trio' that seemed to fix it.
