### ISSUE TITLE
Unclosed httpx.AsyncClient object results in crash for all tried mail addresses

### ISSUE THREAD

**Issue by MisterXY89** [megadose/holehe#34]
**Description:** 
trying to run `holehe test@gmail.com` in terminal, got the following error (for all 4 tried mail addresses):
tried on another Linux-system, one where was python was freshly installed, with Ubuntu 18, got the same error

```
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 108/108 [00:00<00:00, 95365.23it/s]
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/home/USER/.local/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/home/USER/.local/lib/python3.8/site-packages/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/home/USER/.local/lib/python3.8/site-packages/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/home/USER/.local/lib/python3.8/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/home/USER/.local/lib/python3.8/site-packages/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/USER/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USER/.local/bin/holehe", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.8/site-packages/holehe/core.py", line 138, in main
    trio.run(maincore)
  File "/home/USER/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 1928, in run
    raise runner.main_task_outcome.error
  File "/home/USER/.local/lib/python3.8/site-packages/holehe/core.py", line 99, in maincore
    nursery.start_soon(website, email, client, out)
  File "/home/USER/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/USER/.local/lib/python3.8/site-packages/holehe/modules/medical/caringbridge.py", line 32, in caringbridge
    response = await client.post('https://www.caringbridge.org/signin', headers=headers, cookies=cookies, data=data, timeout=2)
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1633, in post
    return await self.request(
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/USER/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/home/USER/.local/lib/python3.8/site-packages/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f578429f940>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

```

**Steps taken to solve it on my end:**
retried multiple times, then reinstalled the package, restarted the pc. 
Internet connection was stable, tried both (W)LAN & mobile hotspot from a smartphone

**OS:**
Ubuntu 20.04.1 LTS

**Python version:**
Python 3.8.5

**Pip version:**
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**package version:**
```
$ pip show holehe
Name: holehe
Version: 1.57.10.2
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/USER/.local/lib/python3.8/site-packages
Requires: tqdm, httpx, trio, termcolor, lxml, bs4
Required-by: 
```

**Comment by megadose** [comment]
https://github.com/megadose/holehe/commit/82644bed2ef54df3fff6b28906ec79c85386082b
it's fixed

**Comment by doggukan** [comment]
im having same issue even with latest.running on termux installed via pip3

**Comment by deltabravozulu** [comment]
I am also having the same issue on Ubuntu, Termux, and Debian.

**Comment by megadose** [comment]
https://github.com/megadose/holehe/commit/160d047fa427494712b2d8f2759fc44cc2ceb499
Normally it's patch, if you still have the problem try to remove your VPN if you have one.
