### ISSUE TITLE
Issue 34 returning again -- Async issues

### ISSUE THREAD

**Issue by deltabravozulu** [megadose/holehe#36]
**Description:** Basically, https://github.com/megadose/holehe/issues/34 is still a problem
Running holehe in conda in Ubuntu, on a fresh Python install in Debian, in termux, etc. yields the following stack trace: 

```
$ holehe test@gmail.com
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ

100%|███████████████████████████████████████████████████| 108/108 [00:00<00:00, 47798.34it/s]
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpcore-0.12.2-py3.9.egg/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpcore-0.12.2-py3.9.egg/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpcore-0.12.2-py3.9.egg/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpcore-0.12.2-py3.9.egg/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpcore-0.12.2-py3.9.egg/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpcore-0.12.2-py3.9.egg/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/holehe/bin/holehe", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.57.10.4.5', 'console_scripts', 'holehe')())
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/holehe-1.57.10.4.5-py3.9.egg/holehe/core.py", line 137, in main
    trio.run(maincore)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/trio-0.17.0-py3.9.egg/trio/_core/_run.py", line 1928, in run
    raise runner.main_task_outcome.error
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/holehe-1.57.10.4.5-py3.9.egg/holehe/core.py", line 98, in maincore
    nursery.start_soon(website, email, client, out)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/trio-0.17.0-py3.9.egg/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/holehe-1.57.10.4.5-py3.9.egg/holehe/modules/social_media/crevado.py", line 18, in crevado
    req = await client.get("https://crevado.com")
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/httpx-0.16.1-py3.9.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7d2963e7a3a0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
```

**Python version:**
Python 3.9.0

**Pip version:**
pip 20.3.3

**Package version:**
```
$ pip show holehe
Name: holehe
Version: 1.57.10.4.5
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: megadose@protonmail.com
License: UNKNOWN
Location: /home/user/miniconda3/envs/holehe/lib/python3.9/site-packages/holehe-1.57.10.4.5-py3.9.egg
Requires: termcolor, tqdm, bs4, httpx, trio
Required-by:
```

**Comment by MisterXY89** [comment]
just tried to run it again, got the same

**Comment by megadose** [comment]
Please try to restart holehe to update it.
