### ISSUE TITLE
Getting Error Upon running latest version

### ISSUE THREAD

**Issue by mohammedoosman** [megadose/holehe#38]
Hi @megadose ,
I am getting the following error whenever i run holehe:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/holehe/core.py", line 140, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 1928, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.9/dist-packages/holehe/core.py", line 99, in maincore
    nursery.start_soon(website, email, client, out)
  File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.9/dist-packages/holehe/modules/social_media/odnoklassniki.py", line 20, in odnoklassniki
    await client.get(OK_LOGIN_URL + '&st.email=' + email, headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError
/usr/local/lib/python3.9/dist-packages/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f754a672dc0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by megadose** [comment]
Fix https://github.com/megadose/holehe/commit/4fec4f5b981109a42aa0109cdc022d4da4819d89
