### ISSUE TITLE
Error everytime I run

### ISSUE THREAD

**Issue by user333222** [megadose/holehe#48]
I'm running: https://cdimage.kali.org/kali-2020.4/kali-linux-2020.4-live-amd64.iso (Debian 9.x Kali)

I downloaded and installed holehe from this git page, (most up to date). 

How do i stop this error? 

**Error**:
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.58.6.5', 'console_scripts', 'holehe')())
  File "/usr/local/lib/python3.8/dist-packages/holehe-1.58.6.5-py3.8.egg/holehe/core.py", line 194, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.8/dist-packages/holehe-1.58.6.5-py3.8.egg/holehe/core.py", line 182, in maincore
    nursery.start_soon(launch_module, website, email, client, out ,args)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.8/dist-packages/holehe-1.58.6.5-py3.8.egg/holehe/core.py", line 148, in launch_module
    await module(email, client, out)
  File "/usr/local/lib/python3.8/dist-packages/holehe-1.58.6.5-py3.8.egg/holehe/modules/jobs/freelancer.py", line 23, in freelancer
    response = await client.post('https://www.freelancer.com/api/users/0.1/users/check?compact=true&new_errors=true', data=data, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1633, in post
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f085e77ac10>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by user333222** [comment]
└─$ pip show holehe                                              130 ⨯ 1 ⚙
Name: holehe
Version: 1.58.6.5
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: megadose@protonmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.8/dist-packages/holehe-1.58.6.5-py3.8.egg
Requires: argparse, bs4, httpx, termcolor, trio
Required-by:

**Comment by megadose** [comment]
Fix
https://github.com/megadose/holehe/commit/0011a86349e39dc8be7dd2e1e64ee8fb8654e57b

**Comment by user333222** [comment]
Still get the error. and updated. 

 pip3 show holehe                                               1 ⨯ 1 ⚙
Name: holehe
Version: 1.58.6.6
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: megadose@protonmail.com
License: UNKNOWN
Location: /home/kali/.local/lib/python3.8/site-packages
Requires: termcolor, argparse, httpx, trio, bs4
Required-by: 


Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.58.6.5', 'console_scripts', 'holehe')())
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 194, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 182, in maincore
    nursery.start_soon(launch_module, website, email, client, out ,args)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 148, in launch_module
    await module(email, client, out)
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/modules/learning/quora.py", line 21, in quora
    r = await client.get("https://fr.quora.com", headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7fa660981f40>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by user333222** [comment]
ahh works now! saw the second update.

**Comment by megadose** [comment]
Fix 
https://github.com/megadose/holehe/commit/0f2c795ac7c18685ce06f45d7f8cddee15be4523

**Comment by user333222** [comment]
Issues again lol. It was just working

Name: holehe
Version: 1.58.6.7
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: megadose@protonmail.com
License: UNKNOWN
Location: /home/kali/.local/lib/python3.8/site-packages
Requires: argparse, termcolor, trio, httpx, bs4
Required-by: 
                                                                           
┌──(kali㉿kali)-[~/Desktop/ipt/holehe]
└─$ holehe mail@mail.com                                   1 ⚙
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 194, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 182, in maincore
    nursery.start_soon(launch_module, website, email, client, out ,args)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 148, in launch_module
    await module(email, client, out)
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/modules/shopping/amazon.py", line 13, in amazon
    req = await client.get(url, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f951a2e4490>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by user333222** [comment]
@megadose

**Comment by megadose** [comment]
Fix
https://github.com/megadose/holehe/commit/429d9d026b75d6426a69b96b5fc25d077ac6eada
Please check your internet conection ;)

**Comment by user333222** [comment]
Weird, my WIFI is fine.

**Comment by user333222** [comment]
My internet connection is fine. Would there be anyway my IP would be blacklisted? Ive attempted to use a VPN aswell and got same results. Not sure what you mean by wifi connection? anyway I show you a test. 

I'm getting different errors each time i attempt to run the script. I really don't think this has to do with my wifi connection. 



(kali㉿kali)-[~/Desktop/ipt/holehe]
└─$ holehe email@mail.com                               1 ⨯ 1 ⚙
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 5, in <module>
    from holehe.core import main
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 203, in <module>
    main()
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 201, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 189, in maincore
    nursery.start_soon(launch_module, website, email, client, out ,args)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 153, in launch_module
    await module(email, client, out)
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/modules/medias/rambler.py", line 24, in rambler
    response = await client.post(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1633, in post
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f4720b48eb0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
                                                                           
┌──(kali㉿kali)-[~/Desktop/ipt/holehe]
└─$ holehe email@mail.com                               1 ⨯ 1 ⚙
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_backends/trio.py", line 165, in open_tcp_stream
    return SocketStream(stream=stream)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore-0.12.2-py3.8.egg/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 5, in <module>
    from holehe.core import main
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 203, in <module>
    main()
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 201, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 189, in maincore
    nursery.start_soon(launch_module, website, email, client, out ,args)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 153, in launch_module
    await module(email, client, out)
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/modules/software/lastpass.py", line 28, in lastpass
    response = await client.get(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7fb16b12ba90>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
                                                                           
ip3 show holehe                                             130 ⨯ 1 ⚙
Name: holehe
Version: 1.58.7
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: megadose@protonmail.com
License: UNKNOWN
Location: /home/kali/.local/lib/python3.8/site-packages
Requires: argparse, trio, bs4, termcolor, httpx
Required-by:

**Comment by user333222** [comment]
@megadose

**Comment by megadose** [comment]
It's OK, it's fixed 
https://github.com/megadose/holehe/commit/556ce7b50265abe590ac20768a25b3db3ac2b090

**Comment by user333222** [comment]
I still get errors here and there, but works better f i keep trying a email more then once. Below are some of the error i was able to produce. 
Thanks for the awesome response/update time. 
@megadose 

**Error**: 
Twitter : @palenath
Github : https://github.com/megadose/holehe
For BTC Donations : 1FHDM49QfZX6pJmhjLE5tB2K6CaTLMZpXZ
Traceback (most recent call last):
  File "/usr/local/bin/holehe", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 209, in main
    trio.run(maincore)
  File "/usr/local/lib/python3.8/dist-packages/trio-0.18.0-py3.8.egg/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 200, in maincore
    out = sorted(out, key=lambda i: i['name'])
  File "/home/kali/.local/lib/python3.8/site-packages/holehe/core.py", line 200, in <lambda>
    out = sorted(out, key=lambda i: i['name'])
KeyError: 'name'
/usr/local/lib/python3.8/dist-packages/httpx-0.16.1-py3.8.egg/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7ffad43e6fa0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.


**Version**:
Name: holehe
Version: 1.58.8.1
Summary: holehe allows you to check if the mail is used on different sites like twitter, instagram , snapchat and will retrieve information on sites with the forgotten password function.
Home-page: http://github.com/megadose/holehe
Author: megadose
Author-email: megadose@protonmail.com
License: UNKNOWN
Location: /home/kali/.local/lib/python3.8/site-packages
Requires: argparse, httpx, trio, termcolor, bs4
Required-by:

**Comment by megadose** [comment]
Fix

**Comment by megadose** [comment]
https://github.com/megadose/holehe/commit/7c8960b864afbc588595e16d5ed31afd3c30c287

**Comment by megadose** [comment]
If you have all the modules that are rate limit you can increase the timeout.
https://github.com/megadose/holehe/commit/cf906c413a8117befd16f0c59fcb57d3f8054928
