### ISSUE TITLE
Trouble with Google CloudShell install

### ISSUE THREAD

**Issue by opticoax747** [megadose/holehe#77]
cloudshell:~/holehe$ holehe
Traceback (most recent call last):
  File "/usr/bin/holehe", line 33, in <module>
    sys.exit(load_entry_point('holehe==1.60.3', 'console_scripts', 'holehe')())
  File "/usr/bin/holehe", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 951, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 542, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for holehe

**Comment by megadose** [comment]
upgrade trio
