### ISSUE TITLE
Metaclass Conflict

### ISSUE THREAD

**Issue by feedesreves** [megadose/holehe#83]
Hi,

I tried to install holehe on my computer, however it gives me this issue when running holehe test@gmail.com or an example.py file with your code...

`TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

How can I fix it?

**Comment by NicolasToussaint** [comment]
Hello,

I have the same behaviour :

**Comment by NicolasToussaint** [comment]
Hello,

I have the same behaviour.
In installed from this GitHub repo, in user home folder.

Python version:
```
$ python3 -V    
Python 3.6.9
```


Full log:
```
$ holehe email@test.com
Traceback (most recent call last):
  File "/home/<user>/.local/bin/holehe", line 11, in <module>
    load_entry_point('holehe==1.60.3', 'console_scripts', 'holehe')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/<user>/.local/lib/python3.6/site-packages/holehe-1.60.3-py3.6.egg/holehe/core.py", line 4, in <module>
    import trio
  File "/home/<user>/.local/lib/python3.6/site-packages/trio-0.20.0-py3.6.egg/trio/__init__.py", line 59, in <module>
    from ._channel import (
  File "/home/<user>/.local/lib/python3.6/site-packages/trio-0.20.0-py3.6.egg/trio/_channel.py", line 112, in <module>
    class MemorySendChannel(SendChannel, metaclass=NoPublicConstructor):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by megadose** [comment]
try to upgrade trio
