### ISSUE TITLE
Crashes at Snapchat and Ebay modules Parse (out.text.split)

### ISSUE THREAD

**Issue by YevgenyMe** [megadose/holehe#89]
**Describe the bug**
during running the "snapchat" example, and Ebay also, the code crashes during the out.text.split answer received with httpx.response.

i didn't check but my guess that there is more modules with the split-fails crashes...

**To Reproduce**
 run the example with the Snapchat module. as shown in the holehe.

**Comment by eccodolf** [comment]
Traceback (most recent call last):
  File "C:\Work\holehe\main.py", line 17, in <module>
    trio.run(main)
  File "C:\Work\holehe\venv\lib\site-packages\trio\_core\_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "C:\Work\holehe\main.py", line 12, in main
    await snapchat(email, client, out)
  File "C:\Work\holehe\venv\lib\site-packages\holehe\modules\social_media\snapchat.py", line 12, in snapchat
    xsrf = req.text.split('data-xsrf="')[1].split('"')[0]
IndexError: list index out of range

**Comment by LucBerge** [comment]
I guess this kind of error can occurs if the website (or the api) has been updated. @megadose maybe we should add a 4th color for failed queries.
